#!/bin/bash

#WARNING: This tool could make or break your changes, so be careful when using it.

#Modify this value to change your projects' location
gitlocation="/home/kolt/Git/"

usage="\nUSAGE: yologit [OPTION]... [DIR]... [URL]\n\tFor help use the --help option.\n"
help="\nyologit commands:\n\n
								\t--good\t\tTutorial comming soon.\n
																 \t\t\tUsage: yologit --good\n\n
								\t--help\t\tShow this menu.\n
																 \t\t\tUsage: yologit --help\n\n
								\t--list\t\tList all your git projects (on your predefined git directory).\n
																 \t\t\tUsage: yologit --list\n\n
								\t--redi\t\tPrepare new project for upload.\n
																 \t\t\tUsage: yologit --redi [DIR]\n\n
								\t--rekt [DIR]\tAdd, commit, pull and push everything in one step.\n
												 				 \t\t\tUsage: yologit --rekt [DIR] --message 'Cute message'\n\n"

if [[ $# -eq 0 ]] ; then
    echo -e $usage
    exit 0

elif [[ $# -eq 1 ]] ; then
		case "$1" in
				--list)
						ls -1 $gitlocation
						;;
				--help)
						echo -e $help
						exit 0
						;;
				*)
						echo -e "\nWrong command. Use 'yologit --help for more information'\n"
						;;
		esac
					
elif [ $# -eq 3 ] && [ $1 = "--redi" ] && [ -d $gitlocation/$2 ] ; then

		git -C $gitlocation/$2 init
		git -C $gitlocation/$2 remote add origin "$3"
		
elif [ $# -eq 4 ] && [ $1 = "--rekt" ] && [ -d $gitlocation/$2 ] && [ $3 = "--message" ] ; then
		
		git -C $gitlocation/$2 add .
		git -C $gitlocation/$2 commit -m "$4"
		git -C $gitlocation/$2 pull origin master
		git -C $gitlocation/$2 push origin master


else
		echo -e "\nWrong command. Use 'yologit --help for more information'\n"
fi
